export const menuItems = [
  // Vegetarian Curries
  {
    id: "1",
    name: "Paneer Tikka Masala",
    description: "Grilled paneer in rich tomato-based creamy sauce",
    price: 380,
    category: "Main Course",
    dietType: "veg",
    foodType: "curry",
    spicyLevel: 2,
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.8,
    isPopular: true,
    preparationTime: 20,
  },
  {
    id: "2",
    name: "Dal Makhani",
    description: "Slow-cooked black lentils and kidney beans in creamy sauce",
    price: 280,
    category: "Main Course",
    dietType: "veg",
    foodType: "curry",
    spicyLevel: 1,
    image:
      "https://images.unsplash.com/photo-1585238341710-4dd0c06ff000?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.6,
    preparationTime: 20,
  },
  {
    id: "3",
    name: "Malai Kofta",
    description:
      "Paneer and vegetable dumplings in creamy coconut tomato sauce",
    price: 340,
    category: "Main Course",
    dietType: "veg",
    foodType: "curry",
    spicyLevel: 1,
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.5,
    preparationTime: 20,
  },
  {
    id: "4",
    name: "Chana Masala",
    description: "Chickpeas in aromatic tomato-based spicy sauce",
    price: 220,
    category: "Main Course",
    dietType: "veg",
    foodType: "curry",
    spicyLevel: 4,
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.4,
    preparationTime: 18,
  },

  // Non-Vegetarian Curries
  {
    id: "5",
    name: "Butter Chicken",
    description: "Tender chicken in creamy tomato butter sauce",
    price: 450,
    category: "Non veg",
    dietType: "non-veg",
    foodType: "curry",
    spicyLevel: 2,
    image:
      "https://images.unsplash.com/photo-1565937927207-6b6b0ce3b4b6?w=500&h=500&fit=crop",
    isVeg: false,
    rating: 4.8,
    isPopular: true,
    preparationTime: 25,
  },
  {
    id: "6",
    name: "Chicken Tikka Masala",
    description: "Grilled chicken in rich tomato-based creamy sauce",
    price: 480,
    category: "Non veg",
    dietType: "non-veg",
    foodType: "curry",
    spicyLevel: 3,
    image:
      "https://images.unsplash.com/photo-1574726894779-28d9f9ecb6fa?w=500&h=500&fit=crop",
    isVeg: false,
    rating: 4.8,
    isPopular: true,
    preparationTime: 28,
  },
  {
    id: "7",
    name: "Fish Curry",
    description: "Fresh fish in aromatic coconut and curry leaf sauce",
    price: 520,
    category: "Non veg",
    dietType: "non-veg",
    foodType: "curry",
    spicyLevel: 3,
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
    isVeg: false,
    rating: 4.7,
    isLimited: true,
    preparationTime: 25,
  },
  {
    id: "8",
    name: "Mutton Rogan Josh",
    description: "Tender mutton pieces in aromatic spiced sauce",
    price: 520,
    category: "Non veg",
    dietType: "non-veg",
    foodType: "curry",
    spicyLevel: 4,
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=500&fit=crop",
    isVeg: false,
    rating: 4.6,
    preparationTime: 35,
  },

  // Rice Dishes
  {
    id: "9",
    name: "Chicken Biryani",
    description: "Fragrant basmati rice cooked with chicken and spices",
    price: 550,
    category: "Non veg",
    dietType: "non-veg",
    foodType: "rice",
    spicyLevel: 3,
    image:
      "https://images.unsplash.com/photo-1631384837185-d1c0a72feafb?w=500&h=500&fit=crop",
    isVeg: false,
    rating: 4.9,
    isPopular: true,
    preparationTime: 30,
  },
  {
    id: "10",
    name: "Vegetable Biryani",
    description: "Mixed vegetables with basmati rice and aromatic spices",
    price: 380,
    category: "Main Course",
    dietType: "veg",
    foodType: "rice",
    spicyLevel: 2,
    image:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.6,
    preparationTime: 30,
  },
  {
    id: "11",
    name: "Prawn Biryani",
    description: "Basmati rice with juicy prawns and fragrant spices",
    price: 650,
    category: "Main Course",
    dietType: "non-veg",
    foodType: "rice",
    spicyLevel: 3,
    image:
      "https://images.unsplash.com/photo-1631384837185-d1c0a72feafb?w=500&h=500&fit=crop",
    isVeg: false,
    rating: 4.8,
    isPopular: true,
    isLimited: true,
    preparationTime: 35,
  },

  // Breads
  {
    id: "12",
    name: "Naan",
    description: "Traditional Indian bread baked in tandoor oven",
    price: 80,
    category: " Main Course",
    dietType: "veg",
    foodType: "bread",
    spicyLevel: 1,
    image:
      "https://images.unsplash.com/photo-1633149159474-0fb84f21c981?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.5,
    preparationTime: 5,
  },
  {
    id: "13",
    name: "Garlic Naan",
    description: "Fluffy naan bread with fresh garlic and herbs",
    price: 120,
    category: " Main Course",
    dietType: "veg",
    foodType: "bread",
    spicyLevel: 1,
    image:
      "https://images.unsplash.com/photo-1633149159474-0fb84f21c981?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.6,
    preparationTime: 8,
  },
  {
    id: "14",
    name: "Chili Naan",
    description: "Spicy naan bread with green chilies and herbs",
    price: 130,
    category: "Main Course",
    dietType: "veg",
    foodType: "bread",
    spicyLevel: 5,
    image:
      "https://images.unsplash.com/photo-1633149159474-0fb84f21c981?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.5,
    preparationTime: 8,
  },

  // Sweets
  {
    id: "15",
    name: "Gulab Jamun",
    description: "Soft milk dumplings soaked in sweet cardamom-flavored syrup",
    price: 150,
    category: " Main Course",
    dietType: "veg",
    foodType: "dessert",
    spicyLevel: 1,
    image:
      "https://images.unsplash.com/photo-1585078519311-83ca8e7efca1?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.7,
    preparationTime: 10,
  },
  {
    id: "16",
    name: "Ras Malai",
    description: "Soft paneer dumplings in sweetened milk with nuts",
    price: 200,
    category: " Main Course",
    dietType: "veg",
    foodType: "dessert",
    spicyLevel: 1,
    image:
      "https://images.unsplash.com/photo-1618449771822-3e2b59f39f2a?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.6,
    preparationTime: 15,
  },
  {
    id: "17",
    name: "Kheer",
    description: "Rice pudding with milk, nuts, and cardamom",
    price: 120,
    category: " Main Course",
    dietType: "veg",
    foodType: "dessert",
    spicyLevel: 1,
    image:
      "https://images.unsplash.com/photo-1618449771822-3e2b59f39f2a?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.5,
    preparationTime: 20,
  },

  // Beverages
  {
    id: "18",
    name: "Mango Lassi",
    description: "Refreshing yogurt-based drink with fresh mango puree",
    price: 120,
    category: "beverage",
    dietType: "veg",
    foodType: "beverage",
    spicyLevel: 1,
    image:
      "https://images.unsplash.com/photo-1618449771822-3e2b59f39f2a?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.5,
    preparationTime: 5,
  },
  {
    id: "19",
    name: "Masala Chai",
    description: "Traditional Indian spiced tea with milk",
    price: 60,
    category: "beverage",
    dietType: "veg",
    foodType: "beverage",
    spicyLevel: 2,
    image:
      "https://images.unsplash.com/photo-1618449771822-3e2b59f39f2a?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.6,
    preparationTime: 8,
  },
  {
    id: "20",
    name: "Sweet Lassi",
    description: "Chilled yogurt-based sweet beverage",
    price: 100,
    category: "beverage",
    dietType: "veg",
    foodType: "beverage",
    spicyLevel: 1,
    image:
      "https://images.unsplash.com/photo-1618449771822-3e2b59f39f2a?w=500&h=500&fit=crop",
    isVeg: true,
    rating: 4.4,
    preparationTime: 5,
  },
  {
    id: "21",
    name: "Paneer Tikka",
    description: "Grilled paneer with spices",
    price: 280,
    category: "Starters",
    dietType: "veg",
    foodType: "appetizer",
    spicyLevel: 2,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500",
    isVeg: true,
    rating: 4.7,
  },
  {
    id: "22",
    name: "Veg Spring Rolls",
    description: "Crispy vegetable rolls",
    price: 220,
    category: "Starters",
    dietType: "veg",
    foodType: "appetizer",
    spicyLevel: 2,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    isVeg: true,
    rating: 4.5,
  },
  {
    id: "23",
    name: "Hara Bhara Kabab",
    description: "Spinach and peas kabab",
    price: 250,
    category: "Starters",
    dietType: "veg",
    foodType: "appetizer",
    spicyLevel: 2,
    image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=500",
    isVeg: true,
    rating: 4.6,
  },
  {
    id: "24",
    name: "Veg Burger",
    description: "Loaded cheese burger",
    price: 180,
    category: "Fast Food",
    dietType: "veg",
    foodType: "appetizer",
    spicyLevel: 1,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
    isVeg: true,
    rating: 4.5,
  },
  {
    id: "25",
    name: "Margherita Pizza",
    description: "Classic cheese pizza",
    price: 320,
    category: "Fast Food",
    dietType: "veg",
    foodType: "appetizer",
    spicyLevel: 1,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
    isVeg: true,
    rating: 4.7,
  },
  {
    id: "26",
    name: "French Fries",
    description: "Crispy golden fries",
    price: 120,
    category: "Fast Food",
    dietType: "veg",
    foodType: "appetizer",
    spicyLevel: 1,
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?w=500",
    isVeg: true,
    rating: 4.4,
  },
  {
    id: "27",
    name: "Greek Salad",
    description: "Fresh vegetables and olives",
    price: 220,
    category: "Healthy",
    dietType: "veg",
    foodType: "appetizer",
    spicyLevel: 1,
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500",
    isVeg: true,
    rating: 4.5,
  },
  {
    id: "28",
    name: "Fruit Bowl",
    description: "Seasonal fresh fruits",
    price: 180,
    category: "Healthy",
    dietType: "veg",
    foodType: "appetizer",
    spicyLevel: 1,
    image: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=500",
    isVeg: true,
    rating: 4.4,
  },
  {
    id: "29",
    name: "Chicken Wings",
    description: "Spicy grilled wings",
    price: 350,
    category: "Non Veg",
    dietType: "non-veg",
    foodType: "appetizer",
    spicyLevel: 4,
    image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=500",
    isVeg: false,
    rating: 4.8,
  },
  {
    id: "30",
    name: "Chicken Tandoori",
    description: "Authentic tandoori chicken",
    price: 420,
    category: "Non Veg",
    dietType: "non-veg",
    foodType: "appetizer",
    spicyLevel: 3,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500",
    isVeg: false,
    rating: 4.9,
  },
  {
    id: "31",
    name: "Mutton Seekh Kabab",
    description: "Juicy minced mutton kabab",
    price: 480,
    category: "Non Veg",
    dietType: "non-veg",
    foodType: "appetizer",
    spicyLevel: 4,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500",
    isVeg: false,
    rating: 4.8,
  },
];

export const dietCategories = [
  { id: "all", label: "All Items", icon: "Utensils" },
  { id: "veg", label: "Vegetarian", icon: "Leaf" },
  { id: "non-veg", label: "Non-Vegetarian", icon: "Flame" },
  { id: "sweets", label: "Sweets", icon: "Cake" },
  { id: "beverages", label: "Beverages", icon: "Coffee" },
  { id: "spicy", label: "Spicy", icon: "Zap" },
];

export const foodTypeCategories = [
  { id: "all", label: "All" },
  { id: "curry", label: "Curries" },
  { id: "rice", label: "Rice Dishes" },
  { id: "bread", label: "Breads" },
  { id: "dessert", label: "Sweets" },
  { id: "appetizer", label: "Appetizers" },
  { id: "beverage", label: "Beverages" },
];

// Banner images for home page
export const bannerImages = [
  {
    id: "1",
    url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&h=400&fit=crop",
    title: "Authentic Indian Flavors",
  },
  {
    id: "2",
    url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200&h=400&fit=crop",
    title: "Premium Quality Ingredients",
  },
  {
    id: "3",
    url: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2070&auto=format&fit=crop",
    title: "Traditional Recipes",
  },
];
